baseURL = 'https://felipe.codes/blog/'
languageCode = 'en'
title = 'blog@felipe.codes'
theme = "archie"
copyright = "© Felipe Cabargas"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 3

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	#subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"
	mathjax = false # enable MathJax support
	katex = false # enable KaTeX support

  # Social Tags

  [[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/felipecabargas"

  [[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/juanpintoduran"

  [[params.social]]
  name = "GitLab"
  icon = "gitlab"
  url = "https://gitlab.com/cabargas/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "https://felipe.codes"
weight = 1

[[menu.main]]
name = "Blog"
url = "/"
weight = 2
